/**
 * Docker Compose 网络配置生成 + 常用网段冲突检测（纯前端）
 */

import { parseCidr, type IPv4CidrInfo } from './cidrCalculator';

export interface DockerNetworkForm {
  networkName: string;
  subnet: string;
  gateway: string;
  driver: 'bridge' | 'overlay' | 'macvlan' | 'host' | 'none';
  attachable: boolean;
  internal: boolean;
  ipRange: string;
}

export interface CommonSubnet {
  name: string;
  cidr: string;
}

/** 常见冲突网段 */
export const COMMON_SUBNETS: CommonSubnet[] = [
  { name: 'Docker 默认 bridge', cidr: '172.17.0.0/16' },
  { name: 'Docker 默认池常见', cidr: '172.18.0.0/16' },
  { name: 'Docker 默认池常见', cidr: '172.19.0.0/16' },
  { name: '家用/小企业 LAN', cidr: '192.168.0.0/16' },
  { name: '私有 A 类', cidr: '10.0.0.0/8' },
  { name: '链路本地', cidr: '169.254.0.0/16' },
  { name: '回环', cidr: '127.0.0.0/8' },
];

export interface ConflictHit {
  name: string;
  cidr: string;
  relation: 'overlap' | 'contains' | 'contained';
}

export function defaultDockerNetworkForm(): DockerNetworkForm {
  return {
    networkName: 'app_net',
    subnet: '172.20.0.0/16',
    gateway: '172.20.0.1',
    driver: 'bridge',
    attachable: false,
    internal: false,
    ipRange: '',
  };
}

function ipToLong(ip: string): number | null {
  const parts = ip.split('.');
  if (parts.length !== 4) return null;
  let n = 0;
  for (const p of parts) {
    if (!/^\d+$/.test(p)) return null;
    const v = Number(p);
    if (v < 0 || v > 255) return null;
    n = ((n << 8) >>> 0) + v;
  }
  return n >>> 0;
}

function rangeOf(info: IPv4CidrInfo): { start: number; end: number } | null {
  const start = ipToLong(info.network);
  const end = ipToLong(info.broadcast);
  if (start === null || end === null) return null;
  return { start, end };
}

function rangesOverlap(a: { start: number; end: number }, b: { start: number; end: number }): boolean {
  return a.start <= b.end && b.start <= a.end;
}

/** 检测与常用网段的重叠 */
export function detectSubnetConflicts(subnet: string, commons: CommonSubnet[] = COMMON_SUBNETS): ConflictHit[] {
  const parsed = parseCidr(subnet);
  if (!parsed.ok || parsed.info.version !== 4) return [];
  const mine = rangeOf(parsed.info);
  if (!mine) return [];

  const hits: ConflictHit[] = [];
  for (const c of commons) {
    const other = parseCidr(c.cidr);
    if (!other.ok || other.info.version !== 4) continue;
    const r = rangeOf(other.info);
    if (!r || !rangesOverlap(mine, r)) continue;
    let relation: ConflictHit['relation'] = 'overlap';
    if (mine.start <= r.start && mine.end >= r.end) relation = 'contains';
    else if (r.start <= mine.start && r.end >= mine.end) relation = 'contained';
    hits.push({ name: c.name, cidr: c.cidr, relation });
  }
  return hits;
}

export function generateComposeNetwork(form: DockerNetworkForm): string {
  const name = form.networkName.trim() || 'app_net';
  const lines: string[] = [];
  lines.push('# Generated by 阿渺工具箱 · Docker 网络配置生成器');
  lines.push('services:');
  lines.push('  # app:');
  lines.push('  #   image: your-image');
  lines.push(`  #   networks: [${name}]`);
  lines.push('');
  lines.push('networks:');
  lines.push(`  ${name}:`);
  lines.push(`    driver: ${form.driver}`);
  if (form.attachable) lines.push('    attachable: true');
  if (form.internal) lines.push('    internal: true');
  lines.push('    ipam:');
  lines.push('      config:');
  lines.push('        - subnet: ' + (form.subnet.trim() || '172.20.0.0/16'));
  if (form.gateway.trim()) {
    lines.push('          gateway: ' + form.gateway.trim());
  }
  if (form.ipRange.trim()) {
    lines.push('          ip_range: ' + form.ipRange.trim());
  }
  return lines.join('\n') + '\n';
}

export function formatConflictText(hits: ConflictHit[]): string {
  if (hits.length === 0) return '未发现与常用网段的重叠。';
  return hits
    .map((h) => {
      const rel =
        h.relation === 'contains'
          ? '包含'
          : h.relation === 'contained'
            ? '被包含'
            : '重叠';
      return `⚠ ${h.name} (${h.cidr}) — ${rel}`;
    })
    .join('\n');
}

/** 根据 subnet 推断建议 gateway（网络地址 + 1） */
export function suggestGateway(subnet: string): string {
  const r = parseCidr(subnet);
  if (!r.ok || r.info.version !== 4) return '';
  const net = ipToLong(r.info.network);
  if (net === null) return '';
  return [
    (net >>> 24) & 255,
    (net >>> 16) & 255,
    (net >>> 8) & 255,
    ((net & 255) + 1) & 255,
  ].join('.');
}
