/**
 * Nginx 配置场景化生成（纯前端）
 * 场景可多选组合：反向代理 / HTTPS / 缓存 / CORS / 负载均衡
 */

export type NginxScenario = 'reverse_proxy' | 'https' | 'cache' | 'cors' | 'load_balance';

export const NGINX_SCENARIO_LABELS: Record<NginxScenario, string> = {
  reverse_proxy: '反向代理',
  https: 'HTTPS',
  cache: '缓存',
  cors: 'CORS',
  load_balance: '负载均衡',
};

export interface NginxFormState {
  scenarios: NginxScenario[];
  serverName: string;
  listenPort: number;
  locationPath: string;
  /** 单后端，如 http://127.0.0.1:3000 */
  upstreamUrl: string;
  /** 负载均衡多后端，每行 host:port */
  backends: string;
  sslCert: string;
  sslKey: string;
  corsOrigin: string;
  cachePath: string;
  cacheValid: string;
}

export function defaultNginxState(): NginxFormState {
  return {
    scenarios: ['reverse_proxy'],
    serverName: 'example.com',
    listenPort: 80,
    locationPath: '/',
    upstreamUrl: 'http://127.0.0.1:3000',
    backends: '127.0.0.1:3000\n127.0.0.1:3001',
    sslCert: '/etc/nginx/ssl/fullchain.pem',
    sslKey: '/etc/nginx/ssl/privkey.pem',
    corsOrigin: '*',
    cachePath: '/var/cache/nginx/app',
    cacheValid: '10m',
  };
}

function indent(block: string, spaces = 4): string {
  const pad = ' '.repeat(spaces);
  return block
    .split('\n')
    .map((l) => (l.trim() ? pad + l : l))
    .join('\n');
}

export function generateNginxConfig(state: NginxFormState): string {
  const scenarios = new Set(state.scenarios);
  const lines: string[] = [];
  lines.push('# Generated by 阿渺工具箱 · Nginx 配置生成器');
  lines.push('# 请按实际路径与安全策略审阅后使用');
  lines.push('');

  if (scenarios.has('cache')) {
    lines.push(`proxy_cache_path ${state.cachePath || '/var/cache/nginx/app'} levels=1:2 keys_zone=app_cache:10m max_size=100m inactive=60m use_temp_path=off;`);
    lines.push('');
  }

  let upstreamName: string | null = null;
  if (scenarios.has('load_balance')) {
    upstreamName = 'app_backend';
    lines.push(`upstream ${upstreamName} {`);
    const hosts = state.backends
      .split(/\r?\n/)
      .map((s) => s.trim())
      .filter(Boolean);
    for (const h of hosts) {
      lines.push(`    server ${h};`);
    }
    if (hosts.length === 0) {
      lines.push('    # server 127.0.0.1:3000;');
    }
    lines.push('}');
    lines.push('');
  }

  const https = scenarios.has('https');
  const listen = https ? 443 : state.listenPort || 80;
  lines.push('server {');
  lines.push(`    listen ${listen}${https ? ' ssl' : ''};`);
  if (https) {
    lines.push('    listen [::]:443 ssl;');
  }
  lines.push(`    server_name ${state.serverName || 'localhost'};`);
  lines.push('');

  if (https) {
    lines.push(`    ssl_certificate     ${state.sslCert};`);
    lines.push(`    ssl_certificate_key ${state.sslKey};`);
    lines.push('    ssl_protocols       TLSv1.2 TLSv1.3;');
    lines.push('    ssl_prefer_server_ciphers on;');
    lines.push('');
  }

  const loc = state.locationPath?.trim() || '/';
  lines.push(`    location ${loc} {`);

  const locBody: string[] = [];

  if (scenarios.has('cors')) {
    const origin = state.corsOrigin || '*';
    locBody.push(`add_header Access-Control-Allow-Origin "${origin}" always;`);
    locBody.push('add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;');
    locBody.push('add_header Access-Control-Allow-Headers "Authorization, Content-Type, X-Requested-With" always;');
    locBody.push('if ($request_method = OPTIONS) {');
    locBody.push('    return 204;');
    locBody.push('}');
  }

  if (scenarios.has('cache')) {
    locBody.push('proxy_cache app_cache;');
    locBody.push(`proxy_cache_valid 200 ${state.cacheValid || '10m'};`);
    locBody.push('proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;');
    locBody.push('add_header X-Cache-Status $upstream_cache_status;');
  }

  if (scenarios.has('reverse_proxy') || scenarios.has('load_balance')) {
    const pass = upstreamName
      ? `http://${upstreamName}`
      : (state.upstreamUrl.trim() || 'http://127.0.0.1:3000');
    locBody.push(`proxy_pass ${pass};`);
    locBody.push('proxy_http_version 1.1;');
    locBody.push('proxy_set_header Host $host;');
    locBody.push('proxy_set_header X-Real-IP $remote_addr;');
    locBody.push('proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
    locBody.push('proxy_set_header X-Forwarded-Proto $scheme;');
    locBody.push('proxy_set_header Upgrade $http_upgrade;');
    locBody.push('proxy_set_header Connection "upgrade";');
  }

  if (locBody.length === 0) {
    locBody.push('# 请至少选择一个场景');
    locBody.push('return 200 "ok\\n";');
    locBody.push('add_header Content-Type text/plain;');
  }

  lines.push(indent(locBody.join('\n'), 8));
  lines.push('    }');
  lines.push('}');

  if (https) {
    lines.push('');
    lines.push('# HTTP → HTTPS 跳转（可选）');
    lines.push('server {');
    lines.push('    listen 80;');
    lines.push(`    server_name ${state.serverName || 'localhost'};`);
    lines.push('    return 301 https://$host$request_uri;');
    lines.push('}');
  }

  return lines.join('\n') + '\n';
}
